name: Build Debug APK on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clean
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          NEW_APK_NAME="app/build/outputs/apk/debug/PR${PR_ID}_debug.apk"
          mv "$APK_PATH" "$NEW_APK_NAME"
          echo "NEW_APK_PATH=$NEW_APK_NAME" >> $GITHUB_ENV

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: PR-${{ github.event.pull_request.number }}
          path: ${{ env.NEW_APK_PATH }}
